# Generated by Django 4.1.3 on 2023-02-14 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='signup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=10)),
                ('fname', models.CharField(max_length=200)),
                ('lname', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('number', models.CharField(max_length=10)),
                ('pass1', models.CharField(max_length=10)),
                ('pass2', models.CharField(max_length=10)),
            ],
        ),
        migrations.AlterField(
            model_name='user',
            name='pic',
            field=models.ImageField(upload_to='images'),
        ),
    ]
