# Generated by Django 4.1.3 on 2023-02-15 00:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('subapp', '0002_signup_alter_user_pic'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='User',
            new_name='Userr',
        ),
    ]
