# Generated by Django 4.1.3 on 2023-03-31 07:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('subapp', '0003_rename_user_userr'),
    ]

    operations = [
        migrations.DeleteModel(
            name='signup',
        ),
    ]
